config/routes.rb
Rails.application.routes.draw do
  root 'deals#index'

  get 'pages/about'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users do
    get :show
  end

  resources :deals do
    resources :comments
    resources :updates
    get :confirmation
    member do
      patch :commit
      patch :flag
      patch :unflag
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  belongs_to :deals
  belongs_to :user
  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_deal, only: [:create, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.deal_id = @deal.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @deal, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to :back, alert: @comment.errors.full_messages.to_sentence }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @deal, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def create_helper

  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_deal
    @deal = Deal.find(params[:deal_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :user_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
  <%= form_for([@deal, @comment]) do |f| %>
    <% if @comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="field">
    <%= f.label :body, "Leave a comment:" , class: "leave-comment" %><br>
    <%= f.text_area :body, rows: "8" %>
  </div>
  <div class="actions">
    <%= f.submit class: "button comment-button" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="deal-show">
  <div class="row">
    <div class="large-12 small-12 columns deal-form">
      <h1>Editing Comment</h1>

      <%= form_for(@comment, url: deal_comment_path) do |f| %>
        <% if @comment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

            <ul>
            <% @comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :body %>
          <%= f.text_area :body, rows: "5" %>
        </div>
        <div class="actions">
          <%= f.submit class: "button user-update-button"%>
        </div>
      <% end %>

      <%= link_to 'Back', @deal %>
    </div>
  </div>
</div>