config/routes.rb
Rails.application.routes.draw do
  root 'deals#index'

  get 'pages/about'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users do
    get :show
  end

  resources :deals do
    resources :comments
    resources :updates
    get :confirmation
    member do
      patch :commit
      patch :flag
      patch :unflag
    end
  end

end

app/models/deal.rb
 class Deal < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  mount_uploader :image, ImageUploader
  has_many :commitments
  has_many :updates, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :owner, class_name: "User"
  has_many :users, through: :commitments
  validates :title, length: { in: 3..60 }
  validates :description, presence: true
  validates :goal, numericality: {  greater_than: 0 }
  validates :amount, numericality: {  greater_than: 0 }
  validates :end, presence: true
  validates :start, presence: true
  validate :date_validation
  validate :image_size

  # http://www.jorgecoca.com/buils-search-form-ruby-rails/
  def self.search(query)
    self.where('title LIKE ?', "%#{query}%").where(published: true).where(private: false)
  end

  def funded?
    self.users.count == self.goal
  end

  def active? # published and not expired
    self.end > Time.now && self.start <= Time.now && self.published
  end

  def archived? # expired deals
    self.end < Time.now && self.published
  end

  def published?
    self.published
  end

  def flagged?
    self.flag
  end

  def progress
    (self.users.count.to_f / self.goal) * 250
  end

  private

  def date_validation
    if self[:end] < self[:start]
      errors[:end] << "End date must come after start date."
      return false
    else
      return true
    end
  end

  def image_size
    if image.size > 5.megabytes
      errors.add(:image, "should be less than 5MB")
    end
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:commit, :show, :edit, :flag, :unflag, :update, :destroy]
  before_action :authenticate_user!, only: [:confirmation, :commit, :new, :edit, :update, :destroy]

  def confirmation
    @deal = Deal.find params[:deal_id]
  end

  def commit
    @deal.users << current_user
    flash[:notice] = "Committed!"
    redirect_to @deal
  end

  def index
    if params[:search]
      @deals = Deal.search(params[:search])
    else
      @deals = policy_scope Deal
    end
  end

  def show
    @comment = Comment.new
    @update = Update.new
    @backers = @deal.users.limit(6)
  end

  def flag
    if @deal.flag
      flash[:notice] = "Thanks for the heads up. This listing has already been reported. An admin will review this listing to make sure it confirms with the Terms of Service."
      redirect_to root_path
    else
      @deal.flag = true
      @deal.save
      flash[:notice] = "Thanks for the heads up. An admin will review this listing to make sure it confirms with the Terms of Service."
      redirect_to root_path
    end
  end

  def unflag
    @deal.flag = false
    if @deal.save
      flash[:notice] = "Unflagged!"
      redirect_to root_path
    end
  end

  def new
    @deal = Deal.new
  end

  def edit
    authorize @deal, :owner?
    authorize @deal, :can_edit?
  end

  def create
    @deal = Deal.new(deal_params)
    @deal.owner_id = current_user.id
    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      authorize @deal, :owner?
      authorize @deal, :can_edit?
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @deal, :owner?
    authorize @deal, :can_edit?
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_deal
    @deal = Deal.find(params[:id])
  end

  def deal_params
    params.require(:deal).permit(:title, :image, :description, :goal, :location, :start, :end, :published, :private, :amount, :owner_id, :flag, :user_id => [])
  end
end

app/helpers/deals_helper.rb
module DealsHelper
  def shorten(text)
    text[0,100]
  end
end

app/views/deals/_flags.html.erb
<p><strong>The following deals have been flagged for review:</strong></p>

<table>
  <tbody>
    <% @deals.where(flag: true).each do |deal| %>
      <tr>
        <td><%= link_to deal.title, deal_path(deal) %></td>
        <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
        <td><%= link_to "Unflag", unflag_deal_path(deal), method: :patch %></td>
        <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/deals/_form.html.erb
<%= form_for(@deal, html: { multipart: true }) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, '*Title' %>
    (60 characters max)
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
  </div>
  <div class="field">
    <%= f.label :description, '*Description' %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :goal, '*Goal' %>
    How many commitments do you need to tip this deal?
    <%= f.number_field :goal %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :start, '*Deal Start Date' %>
    <%= f.date_select :start %>
  </div>
  <div class="field">
    <%= f.label :end, '*Deal End Date (30 day default)' %>
    <%= f.date_select :end, :default => 30.days.from_now %>
  </div>
  <div class="field">
    <%= f.label :private, 'Private?'%>
    Private deals can be shared but are not searchable or listed on the index.
    <%= f.check_box :private %>
  </div>
  <div class="field">
    <%= f.label :amount, '*Amount' %>
    Dollar amount required for each commitment
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :published, 'Published?' %>
    Click here only when you are ready to publish. Published deals will be available to support immediately. To preview your deal, click below with this box unchecked. Deals cannot be unpublished!
    <%= f.check_box :published %>
  </div>

  <div class="actions">
    <%= f.submit "Preview / Publish", class: "button comment-button" %>
  </div>
  <p>* Required fields</p>
<% end %>

app/views/deals/confirmation.html.erb
<div class="deal-show">
  <div class="row">
    <div class="large-12 small-12 columns confirm-page text-center">
      <div class="panel">
        <h1>Confirmation Page</h1>

        <p>You are committing to:</p>

        <p><span class="confirm-amount">$<%= @deal.amount %></span></p>

        <p>You will not be charged until the deal is tipped.</p>

        <p>Are you sure?</p>

        <p>
          <%= link_to commit_deal_path(@deal), method: :patch, class: "paypal" do %>
            <%= image_tag('paypal.gif', alt: "Paypal") %>
          <% end %>
        </p>

        <%= link_to "Back", @deal %>
      </div>
    </div>
  </div>
</div>

app/views/deals/edit.html.erb
<div class="deal-show">
  <div class="row">
    <div class="large-12 small-12 columns deal-form">
      <h1>Editing Deal</h1>

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/deals/index.html.erb
  <div class="billboard">
    <div class="text-container">
    </div>
    <h1>
      Dream it. Share it. Fund it.
      <p>Harness the power of crowdsourcing to turn your dreams into reality.</p>
    </h1>
    <% if !user_signed_in? %>
      <%= link_to "Sign Up for Free!", new_user_registration_path, class: "button large sign-up-btn" %>
    <% else %>
      <p class="welcome">Welcome back, <%= current_user.name %>!</p>
    <% end %>
  </div>

  <div id="flags" class="row">
    <div class="large-9 columns">
      <% if current_user %>
        <% if current_user.admin? && Deal.where(flag: true).count > 0 %>
          <h3>Admin Alert:</h3>
          <%= render 'deals/flags' %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="row deal-boxes">
    <h4 class="sub-title">Recent Deals</h4>
    <% @deals.each do |deal| %>
      <% if deal.active? %>
        <div class="large-4 medium-5 small-6-centered columns boxes">
          <% if deal.image? %>
            <div class="image-box">
              <%= image_tag(deal.image.url, id: 'deal-image') %>
            </div>
          <% else %>
            <img src="http://placehold.it/320x200">
          <% end %>
          <div class="deal-details">
            <h4><%= link_to deal.title, deal %></h4>
            <%= shorten(deal.description) %>...<br>
            <h5><%= deal.users.count %> Committed!</h5>

            <div id="progress-bar">
              <span class="so-far" style="width: <%= deal.progress %>px">
              </span>
            </div>

          <span class="location"><%= deal.location %> /
            <% if deal.funded? %>
              Funded!
            <% else %>
              <%= time_ago_in_words(deal.end) %> left</span>
            <% end %>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>

app/views/deals/new.html.erb
<div class="deal-show">
  <div class="row">
    <div class="large-12 small-12 columns deal-form">
      <h1>New Deal</h1>

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/deals/show.html.erb
<div class="deal-show">
  <div class="row">
      <div class="large-12 small-12 columns draft-warning">
        <% if !@deal.published %>
          <h3>This Deal is Not Yet Published! Review your deal and click "edit" to make any changes and publish. Deals cannot be changed after publication, except by an admin.</h3>
        <% end %>
      </div>
    </div>

<div class="row">
  <div class="large-12 small-12 columns text-right">
    <div class="control">
        <% if policy(@deal).owner? && !@deal.published || policy(@deal).is_admin? %>
          <%= link_to 'Edit', edit_deal_path(@deal) %> &nbsp;|
          <%= link_to 'Destroy', @deal, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
    </div>
  </div>
</div>

<div class="row">
  <% if @deal.image? %>
    <div class="large-6 columns deal-large-image">
      <%= image_tag(@deal.image.url, id: 'deal-image') if @deal.image? %><br>
    </div>
  <% else %>
    <div class="large-6 columns">
      <img src="http://placehold.it/500x300">
    </div>
  <% end %>
  <div class="large-6 columns">
    <div class="panel">
      <h4>
        <%= @deal.title %><br>
        <%= link_to @deal.owner.name, @deal.owner, class: "deal-owner-name" %>
        <hr/>
      </h4>
      <p>Commitments Needed:
      <%= @deal.goal %> at $<%= @deal.amount %></p>
    <% if !@deal.funded? && @deal.active? %>
      <%= link_to "Commit!", deal_confirmation_path(@deal), class: "button expand deal-button" %>
    <% else %>
      <p>This deal has ended!</p>
    <% end %>
      <h4>Progress to Goal:</h4>
      <%= @deal.funded? ? "Funded!" : "#{@deal.users.count} out of #{@deal.goal}" %>

        <div id="graph" data-goal="<%= @deal.goal %>" data-users="<%= @deal.users.count %>">
        </div>

        <p class="location-time">
          <%= @deal.location %> /
          <% if @deal.active? %>
            <%= time_ago_in_words(@deal.end) %> left
          <% else %>
            Closed
          <% end %>
        </p>
      </div>
  </div>
</div>

<div class="row">
  <div class="large-12 small-12 columns deal-desc-show">
    <div class="panel">
      <h4>
        Description
        <hr/>
      </h4>
      <h5 class="subheader"><%= @deal.description %></h5>
      <%= social_share_button_tag(@deal.title) %>
      <%= link_to "Flag", flag_deal_path(@deal), method: :patch, class: "flag-deal" %>
    </div>
  </div>
</div>

  <div class="row">
    <div class="large-6 small-6 columns">
      <%= render partial: 'comments/form', deal: @deal %>
    </div>
    <div class="large-6 small-6 columns">
    <div class="panel">
      <h4>Updates</h4>
      <h6 class="subheader">
        <% @deal.updates.each do |update| %>
            <p>
              <strong>Updated <%= time_ago_in_words(update.created_at) %> ago</strong><br>
              <%= update.content %><br>
              <% if policy(update).owner? || policy(@deal).is_admin? %>
                <%= link_to "Edit", edit_deal_update_path(@deal, update) %> |
                <%= link_to "Destroy", [@deal, update], method: :delete, data: { confirm: "Are you sure?" } %>
              <% end %>
            </p>
          <% end %>
        </h6>
        <div id="owner-actions">
        <% if policy(@deal).owner? %>
          <%= link_to 'Post Update', new_deal_update_path(@deal, @update), class: "button deal-button" %>
        <% end %>
      </div>
    </div>
    </div>
  </div>

  <% if !@deal.users.empty? %>
    <div class="row">
      <div class="large-12 columns backers">
      <h4>Backers</h4>

      <% @backers.each do |user| %>
        <div class="large-2 small-2 columns text-center">
          <%= link_to (image_tag user.gravatar_url), user %><br>
          <strong><%= link_to user.name, user %></strong>
        </div>
      <% end %>
      </div>
    </div>
  <% end %>

    <% if @deal.private %>
      <strong>This deal has been flagged as private. Only visitors with the link can access it. Please share with caution.</strong>
    <% end %>
    <br>
    <br>

  </div>

<div id="comments" class="row">
  <div class="large-12 columns">
    <hr>
    <h4>Comments:</h4>

    <% if !@deal.comments.empty? %>
      <% @deal.comments.each do |comment| %>
      <div class="panel">
        <p><strong><%= link_to comment.user.name, comment.user %></strong><br>
          <strong>Created <%= time_ago_in_words(comment.created_at) %> ago</strong><br>
          <%= comment.body %><br>
          <%= link_to "Edit", edit_deal_comment_path(@deal, comment) %>
        </p>
      </div>
      <% end %>
    <% else %>
      No Comments
    <% end %>
  </div>
</div>
</div>