config/routes.rb
Rails.application.routes.draw do
  root 'deals#index'

  get 'pages/about'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users do
    get :show
  end

  resources :deals do
    resources :comments
    resources :updates
    get :confirmation
    member do
      patch :commit
      patch :flag
      patch :unflag
    end
  end

end

app/views/layouts/_flash.html.erb
<!-- Flash message code found at http://railsapps.github.io/rails-foundation.html -->
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'notice' : 'error' %>">
      <%= content_tag :div, msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  © 2015 UFundIt&nbsp; | &nbsp;<%= link_to "About", pages_about_path %>
</footer>

app/views/layouts/_header.html.erb
<div class="fixed">
  <nav class="top-bar" data-topbar role="navigation">
    <!-- Title -->
    <ul class="title-area">
      <li class="name"><h1><%= link_to "UFundIt", root_path %></h1></li>

      <!-- Mobile Menu Toggle -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <!-- Top Bar Section -->
    <section class="top-bar-section">

      <!-- Top Bar Left Nav Elements -->
      <ul class="left">

        <!-- Search | has-form wrapper -->
        <li class="has-form">
          <div class="row collapse">
            <div class="large-8 small-9 columns">
              <%= form_tag deals_path, :method => 'get' do %>
                  <%= text_field_tag :search, params[:search], :placehoder => 'Search items here' %>
            </div>
            <div class="large-4 small-3 columns">
              <%= submit_tag "Search", :name => nil, class: "button search" %>
            </div>
            <% end %>
          </div>
        </li>
        <li class="divider"></li>
        <li style="background: transparent">
          <%= link_to "About Us", pages_about_path %>
        </li>
        <li class="divider"></li>
      </ul>

      <!-- Top Bar Right Nav Elements -->
      <ul class="right">
        <!-- Divider -->
        <li class="divider"></li>
        <li style="background: transparent">
          <%= link_to "New Deal", new_deal_path %>
        </li>
        <li class="divider"></li>

        <!-- Anchor -->
        <% if current_user && user_signed_in? %>
          <li style="background: transparent">
            <%= link_to 'My Profile', current_user %>
          </li>
          <li class="divider"></li>
          <li style="background: transparent">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li style="background: transparent">
            <%= link_to 'Sign Up', new_user_registration_path %>
          </li>
          <li class="divider"></li>
          <li style="background: transparent">
            <%= link_to 'Log In', new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "UFundIt" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <%= render 'layouts/flash' %>

      <%= yield %>

    <%= render 'layouts/footer' %>

  </body>
</html>